config/routes.rb
Rails.application.routes.draw do
  resources :boletims
  resources :aprovado_boletims
  resources :reprovado_boletims
  root to: "boletims#index"

end

app/models/boletim.rb
class Boletim < ActiveRecord::Base

    def self.search(nome)
        if nome.present?
            where(nome: nome)
        else
            all
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/aprovado_boletims_controller.rb
class AprovadoBoletimsController < ApplicationController
    def index
        @aprovado_boletims = Boletim.where(aprovado: true)
    end
end

app/controllers/boletims_controller.rb
class BoletimsController < ApplicationController
  before_action :set_boletim, only: [:show, :edit, :update, :destroy]

  # GET /boletims
  # GET /boletims.json
  def index
    @boletims = Boletim.search(params[:nome])
  end

  # GET /boletims/1
  # GET /boletims/1.json
  def show
  end

  # GET /boletims/new
  def new
    @boletim = Boletim.new
  end

  # GET /boletims/1/edit
  def edit
  end

  # POST /boletims
  # POST /boletims.json
  def create
    @boletim = Boletim.new(boletim_params)

    respond_to do |format|
      if @boletim.save
        format.html { redirect_to @boletim, notice: 'Boletim was successfully created.' }
        format.json { render :show, status: :created, location: @boletim }
      else
        format.html { render :new }
        format.json { render json: @boletim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boletims/1
  # PATCH/PUT /boletims/1.json
  def update
    respond_to do |format|
      if @boletim.update(boletim_params)
        format.html { redirect_to @boletim, notice: 'Boletim was successfully updated.' }
        format.json { render :show, status: :ok, location: @boletim }
      else
        format.html { render :edit }
        format.json { render json: @boletim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boletims/1
  # DELETE /boletims/1.json
  def destroy
    @boletim.destroy
    respond_to do |format|
      format.html { redirect_to boletims_url, notice: 'Boletim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boletim
      @boletim = Boletim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boletim_params
      params.require(:boletim).permit(:nome, :idade, :masculino, :feminino, :email, :faltas, :turma, :turno, :aprovado, :reprovado)
    end
end

app/controllers/reprovado_boletims_controller.rb
class ReprovadoBoletimsController < ApplicationController
    def index
        @reprovado_boletims = Boletim.where(reprovado: true)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aprovado_boletims_helper.rb
module AprovadoBoletimsHelper
end

app/helpers/boletims_helper.rb
module BoletimsHelper
end

app/helpers/reprovado_boletims_helper.rb
module ReprovadoBoletimsHelper
end

app/views/aprovado_boletims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Aprovados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Masculino</th>
      <th>Feminino</th>
      <th>Email</th>
      <th>Faltas</th>
      <th>Turma</th>
      <th>Turno</th>
      <th>Aprovado</th>
      <th>Reprovado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aprovado_boletims.each do |boletim| %>
      <tr>
        <td><%= boletim.nome %></td>
        <td><%= boletim.idade %></td>
        <td><%= boletim.masculino %></td>
        <td><%= boletim.feminino %></td>
        <td><%= boletim.email %></td>
        <td><%= boletim.faltas %></td>
        <td><%= boletim.turma %></td>
        <td><%= boletim.turno %></td>
        <td><%= boletim.aprovado %></td>
        <td><%= boletim.reprovado %></td>
        <td><%= link_to 'Detalhes', boletim %></td>
        <td><%= link_to 'Editar', edit_boletim_path(boletim) %></td>
        <td><%= link_to 'Apagar', boletim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3>
<%= link_to 'Cadastro', new_boletim_path %>
<%= link_to 'Inicio', boletims_path %>
</h3>

app/views/boletims/_form.html.erb
<%= form_for(@boletim) do |f| %>
  <% if @boletim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boletim.errors.count, "error") %> prohibited this boletim from being saved:</h2>

      <ul>
      <% @boletim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :masculino %><br>
    <%= f.check_box :masculino %>
  </div>
  <div class="field">
    <%= f.label :feminino %><br>
    <%= f.check_box :feminino %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :faltas %><br>
    <%= f.number_field :faltas %>
  </div>
  <div class="field">
    <%= f.label :turma %><br>
    <%= f.number_field :turma %>
  </div>
  <div class="field">
    <%= f.label :turno %><br>
    <%= f.text_field :turno %>
  </div>
  <div class="field">
    <%= f.label :aprovado %><br>
    <%= f.check_box :aprovado %>
  </div>
  <div class="field">
    <%= f.label :reprovado %><br>
    <%= f.check_box :reprovado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boletims/edit.html.erb
<h1>Editar Boletim Escolar</h1>
<h2>
<%= render 'form' %>

<%= link_to 'Detalhes', @boletim %> 
<%= link_to 'Inicio', boletims_path %>
<%= link_to 'Cadastro', new_boletim_path %>
</h2>

app/views/boletims/index.html.erb
<p id="notice"><%= notice %></p>
<head>
<style>
body  {
    background-image: url("escolar2.jpg");
    background-color: #FFFFFF;
    background-repeat: no-repeat, repeat;
    background-position: bottom right;  
    background-position: right top; 
}
</style>
</head>
<h1>Lista de Boletim Escolar</h1>

      <form>
        <legend><h4>Pesquisar Aluno</h4></legend>
          <input type='text' value='<%= params[:nome] %>' name='nome' >
      </form>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Masculino</th>
      <th>Feminino</th>
      <th>Email</th>
      <th>Faltas</th>
      <th>Turma</th>
      <th>Turno</th>
      <th>Aprovado</th>
      <th>Reprovado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boletims.each do |boletim| %>
      <tr>
        <td><%= boletim.nome %></td>
        <td><%= boletim.idade %></td>
        <td><%= boletim.masculino %></td>
        <td><%= boletim.feminino %></td>
        <td><%= boletim.email %></td>
        <td><%= boletim.faltas %></td>
        <td><%= boletim.turma %></td>
        <td><%= boletim.turno %></td>
        <td><%= boletim.aprovado %></td>
        <td><%= boletim.reprovado %></td>
        <td><%= link_to 'Detalhes', boletim %></td>
        <td><%= link_to 'Editar', edit_boletim_path(boletim) %></td>
        <td><%= link_to 'Apagar', boletim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h3>
<%= link_to 'Cadastro', new_boletim_path %>
<%= link_to 'Inicio', boletims_path %>
</h3>

</body>
</html>

app/views/boletims/new.html.erb
<h1>Cadastro de Boletim Escolar</h1>

<h2>
<%= render 'form' %>
<h2>
<%= link_to 'Inicio', boletims_path %>
<%= link_to 'Cadastro', new_boletim_path %>
</h2>

app/views/boletims/show.html.erb
<h1>Detalhes do Boletim Escolar</h1>
<p id="notice"><%= notice %></p>
<h2>
<p>
  <strong>Nome:</strong>
  <%= @boletim.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @boletim.idade %>
</p>

<p>
  <strong>Masculino:</strong>
  <%= @boletim.masculino %>
</p>

<p>
  <strong>Feminino:</strong>
  <%= @boletim.feminino %>
</p>

<p>
  <strong>Email:</strong>
  <%= @boletim.email %>
</p>

<p>
  <strong>Faltas:</strong>
  <%= @boletim.faltas %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @boletim.turma %>
</p>

<p>
  <strong>Turno:</strong>
  <%= @boletim.turno %>
</p>

<p>
  <strong>Aprovado:</strong>
  <%= @boletim.aprovado %>
</p>

<p>
  <strong>Reprovado:</strong>
  <%= @boletim.reprovado %>
</p>

<%= link_to 'Editar', edit_boletim_path(@boletim) %> 
<%= link_to 'Inicio', boletims_path %>
<%= link_to 'Cadastro', new_boletim_path %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="stylesheet" href="vendor/assets/stylesheets/bootstrap.css">
  <link href="stylesheet" href="app/assets/stylesheets/styles.css">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reprovado_boletims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Reprovados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Masculino</th>
      <th>Feminino</th>
      <th>Email</th>
      <th>Faltas</th>
      <th>Turma</th>
      <th>Turno</th>
      <th>Aprovado</th>
      <th>Reprovado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reprovado_boletims.each do |boletim| %>
      <tr>
        <td><%= boletim.nome %></td>
        <td><%= boletim.idade %></td>
        <td><%= boletim.masculino %></td>
        <td><%= boletim.feminino %></td>
        <td><%= boletim.email %></td>
        <td><%= boletim.faltas %></td>
        <td><%= boletim.turma %></td>
        <td><%= boletim.turno %></td>
        <td><%= boletim.aprovado %></td>
        <td><%= boletim.reprovado %></td>
        <td><%= link_to 'Detalhes', boletim %></td>
        <td><%= link_to 'Editar', edit_boletim_path(boletim) %></td>
        <td><%= link_to 'Apagar', boletim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>
<%= link_to 'Cadastro', new_boletim_path %>
<%= link_to 'Inicio', boletims_path %>
</h3>